[package]
name = "quamatic/aether-vide"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Aether = "quamatic/aether@^0.1"
Vide = "centau/vide@^0.3"
