[package]
name = "quamatic/aether-react"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Aether = "quamatic/aether@^0.1"
React = "jsdotlua/react@^17"
