name: Deploy Documentation to Github Pages

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: write

jobs:
    deploy:
        name: Deploy to Github Pages
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: website

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 9.12.1
                  run_install: false

            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build website
              run: pnpm run build

            - name: Deploy to Github Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
